version: "3.1"

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  app:
    build: .
    restart: always
    tty: true
    ports:
      - 65:80
    links:
      - elasticsearch
    volumes:
      - .:/app

