version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  seedr:
    container_name: seedr
    build: ./seedr
    restart: always
    tty: true
    links:
      - elasticsearch
    volumes:
      - ./seedr:/app
    networks:
      - esnet
  python_client:
    build:
      context: ./python-client
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 65:80
    links:
      - elasticsearch
    volumes:
      - ./python-client:/app
    networks:
      - esnet
  php-cli:
    build: ./php-client
    tty: true
    ports:
      - "89:80"
    expose:
      - "9000"
      - "443"
    volumes:
        - ./php-client:/var/www/php-cli
    links:
        - elasticsearch
    networks:
        - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: